import {
  Antenna,
  BarChart3,
  Banknote,
  Bell,
  Book,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  Car,
  Columns3,
  Download,
  File,
  FileDown,
  FilePlus,
  Files,
  FileSearch,
  FileSignature,
  FileText,
  GraduationCap,
  HeartPulse,
  IdCard,
  Key,
  LayoutDashboard,
  LineChart,
  Map,
  MapPin,
  Medal,
  MessageSquare,
  Network,
  Newspaper,
  Receipt,
  Scan,
  Search,
  SearchCode,
  Send,
  Settings,
  Star,
  Table,
  Table2,
  Ticket,
  TrendingUp,
  Trophy,
  Truck,
  Upload,
  UserPlus,
  Users,
  Wallet,
  Zap,
} from 'lucide-react'

const REGISTRY: Record<string, React.ComponentType<{ className?: string }>> = {
  antenna: Antenna,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  book: Book,
  'book-open': BookOpen,
  building: Building2,
  calculator: Calculator,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  car: Car,
  columns: Columns3,
  download: Download,
  file: File,
  'file-down': FileDown,
  'file-plus': FilePlus,
  'file-search': FileSearch,
  'file-signature': FileSignature,
  'file-text': FileText,
  files: Files,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  'id-card': IdCard,
  key: Key,
  'layout-dashboard': LayoutDashboard,
  'line-chart': LineChart,
  map: Map,
  'map-pin': MapPin,
  medal: Medal,
  'message-square': MessageSquare,
  network: Network,
  newspaper: Newspaper,
  receipt: Receipt,
  scan: Scan,
  search: Search,
  'search-code': SearchCode,
  send: Send,
  settings: Settings,
  star: Star,
  table: Table,
  'table-2': Table2,
  ticket: Ticket,
  'trending-up': TrendingUp,
  trophy: Trophy,
  truck: Truck,
  upload: Upload,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  zap: Zap,
}

export default function MenuIcon({
  name,
  className = 'w-4 h-4',
}: {
  name: string
  className?: string
}) {
  const Cmp = REGISTRY[name] ?? File
  return <Cmp className={className} />
}
